### ISSUE TITLE
ST3: Unable to load diagram plugin, check console for details.

### ISSUE THREAD

**Issue by todorvlaev** [jvantuyl/sublime_diagram_plugin#12]
Hi,

I tried installing the plugin with Package Control (v2.0.0-alpha9) on Sublime Text 3 (build 3047), but get the following error:

> reloading plugin Diagram.diagram_plugin
> Viewer Setting: Preview
> Loading processor class: <class 'Diagram.diagram.plantuml.PlantUMLProcessor'>
> Unable to load processor: <class 'Diagram.diagram.plantuml.PlantUMLProcessor'>
> Traceback (most recent call last):
>   File "diagram in /home/todor/.config/sublime-text-3/Installed Packages/Diagram.sublime-package", line 34, in setup
>   File "diagram.plantuml in /home/todor/.config/sublime-text-3/Installed Packages/Diagram.sublime-package", line 41, in load
>   File "diagram.plantuml in /home/todor/.config/sublime-text-3/Installed Packages/Diagram.sublime-package", line 81, in find_plantuml_jar
> Exception: can't find plantuml-7963.jar
> error: Unable to load diagram plugin, check console for details.
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 115, in reload_plugin
>     m.plugin_loaded()
>   File "diagram_plugin in /home/todor/.config/sublime-text-3/Installed Packages/Diagram.sublime-package", line 26, in plugin_loaded
>   File "diagram in /home/todor/.config/sublime-text-3/Installed Packages/Diagram.sublime-package", line 41, in setup
> Exception: No working processors found!

Hope this is useful to you in case anyone else faces the same problem.

**Comment by joewilliams** [comment]
I have the same issue.

**Comment by jvantuyl** [comment]
I can't reproduce this.  Can either of you give me a little more information about your environment?  Is that the whole error message?

**Comment by tooh** [comment]
File "/Users/peter/Library/Application Support/Sublime Text 3/Packages/Diagram/diagram/__init__.py", line 49, in setup
    raise Exception('No working processors found!')
Exception: No working processors found!
SublimeLinter: debug mode: off 
Package Control: Skipping automatic upgrade, last run at 2015-07-01 14:53:38, next run at 2015-07-01 15:53:38 or after

**Comment by jvantuyl** [comment]
What version of MacOS X is that @tooh?

**Comment by tooh** [comment]
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46

**Comment by jguillon** [comment]
I had the same issue and solved it by installing GraphViz (`brew install graphviz`).

**Comment by tooh** [comment]
Did 
```
brew install graphviz
```
It seems that this partly solves my problem. The plugin seems active now.
I have another problem and will open separate issue for that.

**Comment by idevz** [comment]
hi,@tooh My situation is when I did ```brew install graphviz``` it doenn't work util I run ```brew link --overwrite graphviz``` after this. And Now It works

**Comment by glumes** [comment]
I have the same issue too.And I still can't solve it.

**Comment by woshidama323** [comment]
hi, did everyone have the problem like this  ?
Loading processor class: <class 'sublime_diagram_plugin.diagram.plantuml.PlantUMLProcessor'>
Unable to load processor: <class 'sublime_diagram_plugin.diagram.plantuml.PlantUMLProcessor'>
Traceback (most recent call last):
  File "D:\BACKUP-APP\SublimeText\Data\Packages\sublime_diagram_plugin\diagram\__init__.py", line 44, in setup
    proc.load()
  File "D:\BACKUP-APP\SublimeText\Data\Packages\sublime_diagram_plugin\diagram\plantuml.py", line 56, in load
    self.check_dependencies()
  File "D:\BACKUP-APP\SublimeText\Data\Packages\sublime_diagram_plugin\diagram\plantuml.py", line 70, in check_dependencies
    raise Exception("can't find Java")
Exception: can't find Java
error: Unable to load diagram plugin, check console for details.

ENV: windows 7-64x     sublime 3

and the java is ok
C:\Windows\System32>java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Comment by leauge7** [comment]
@woshidama323  Maybe java 1.6 will be working correctly.

**Comment by ascientist** [comment]
A proper` sudo apt-get install graphviz` solve the problem in my case (Ubuntu 16.04). 
I had previoulsy install the plugin via `Package Control: Add repository` and `Package Control: Install Package`

**Comment by rikpires** [comment]
Just share some information. I also meet this problem, and find out I don't install proper java version in Ubuntu.

**Comment by linxyfruitday** [comment]
I fixed the bug. 
1.brew install graphviz
2.restart sublime
3.select code and 'alt+d'
4.enjoy it.

**Comment by jvantuyl** [comment]
It looks like this was a missing graphviz install. I can’t really do much about this and I do list it as a dependency in the README. I think that’s as fixed as this can be right now.

**Comment by XUPTLiYipeng** [comment]
1.I've installed graphviz certainly
2.I've tried many possible solutions appeared in this issue
However it still doesn't work for me :(
my laptop is Apple MacBookPro with ARM arch M1 chip , whose system version is macOS Sonna 14.7.8
